### ISSUE TITLE
Fastbootd does not work

### ISSUE THREAD

**Issue by Rogerjr442200** [juic3b0x/twrp12_device_motorola_denver#2]
You can fix it with this in device.mk instead of 1.0
Remove your fastbootd and put this
# Fastbootd
PRODUCT_PACKAGES += \
    android.hardware.fastboot@1.1-impl-mock \
    android.hardware.fastboot@1.1

**Comment by juic3b0x** [comment]
I'll give it a try and see how it works!

**Comment by juic3b0x** [comment]
https://github.com/juic3b0x/twrp12_device_motorola_denver/commit/3988d44b12ffb852c9f190bea9c870fac775cd3c
